language: python
sudo: required
python:
  - "3.6"
install:
  - sudo apt-get install -y wget unzip
  - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - sudo unzip terraform.zip -d /usr/local/bin/
  - sudo pip3 install -y aws
